add learnt phrases
onja-org/malagasy-rn-Lead pull request #5
Opened 2021-05-26 09:13 UTC by Tanosimboangy

Hey Team

We've added learnt phrases and store them in async storage and in redux state. Please have a look and give some comments if necessary. Please, feel free to give feed back.

Thanks in advance.

2021-05-27 04:28 UTC, Voninkazo commented on Root.js
> +// import Storybook from "./storybook";
This should be removed because it is not used

2021-05-27 04:28 UTC, Voninkazo commented on src/redux/reducers/index.js
>  // import all of constat case name for the swich
There are spelling mistakes in that line

2021-05-27 04:28 UTC, Voninkazo commented on src/screens/Learning.js
> +        // TODO add to learned
Delete the TODO because you already implement the code here

2021-05-27 04:28 UTC, Voninkazo commented on src/screens/Learning.js
> +        // TODO add to seen
Delete the TODO because you already implement the code here

2021-05-27 07:16 UTC, andrzej-onja requested changes

2021-05-27 07:16 UTC, andrzej-onja commented on Root.js
> +// setting up async storage
do you need this comment?

2021-05-27 07:16 UTC, andrzej-onja commented on src/data/dataUtils.js
> +  return phrasesData.phrasesId;
why this change ? It shouldn't change

2021-05-27 07:16 UTC, andrzej-onja commented on src/redux/constants/index.js
> +export const NEW_KEY_PHRASES = '@NewPhrases';
Please move NEW_KEY_PHRASES to utils/storag

2021-05-27 07:16 UTC, andrzej-onja commented on src/screens/Learning.js
>      [currentPhrase, setDisableAllOptions, answerOptions],
seenPhrases and learntPhrases have to be added to dependency array of the callback. Not doing this can lead to unexpected behavior and hard to debug issues
[currentPhrase, setDisableAllOptions, answerOptions, **seenPhrases, learntPhrases** ],

2021-06-03 07:38 UTC, andrzej-onja commented on src/redux/actions/index.js
> +export function addLearntPhrases(phrase) {
addLearntPhrase without 's'

2021-06-03 07:38 UTC, andrzej-onja commented on src/redux/actions/index.js
> +export function updateLearntPhrases(wrongPhrase) {
how about renaming it to removeLearntPhrase(phrase)

so it becomes universal

2021-06-03 12:23 UTC, andrzej-onja approved these changes

2021-06-04 04:02 UTC, Voninkazo approved these changes

2021-06-04 04:06 UTC, tsipoy approved these changes

2021-06-04 04:06 UTC, tsipoy commented on src/screens/Home.js
> +  const openCategoryPhrases = item => {
Could you change the item to another name. Item is more broadly.

2021-06-04 04:09 UTC, merged